"""Public kOA boundary for directional interchange with the external UCKK platform."""

from .bootstrap import AdapterConfig, UckkAdapter, build_adapter
from .capabilities import (
    CapabilityResolver,
    CapabilityState,
    DirectionCapabilities,
    UckkCapabilitySnapshot,
)
from .client import (
    IMPORT_OPERATIONS,
    PUBLISH_OPERATIONS,
    CallResult,
    CircuitBreaker,
    CircuitBreakerPolicy,
    CircuitSnapshot,
    CircuitState,
    ClientConfigurationError,
    DeadLetterSink,
    DirectionalClient,
    ExternalCallError,
    FailureClass,
    ProbeResult,
    ReceiptSink,
    ResiliencePolicy,
    RetryPolicy,
    UckkClient,
    UckkTransport,
)
from .health import DirectionHealth, HealthChecker, HealthState, UckkHealthReport
from .moodle_client import (
    ALLOWED_OPERATIONS,
    BinaryPayload,
    HttpTransport,
    MoodleClient,
    MoodleClientError,
    MoodleEndpoint,
    MoodleHealth,
    MoodleOperation,
    SecretProvider,
    TransportResponse,
)
from .publication import PublicationError, PublicationService, StoredPublication
from .receipts import (
    Direction,
    ItemOutcome,
    ReceiptValidationError,
    TerminalOutcome,
    TerminalReceipt,
    build_dead_letter_record,
    build_terminal_receipt,
    canonical_json,
    payload_digest,
    utc_timestamp,
)

__all__ = (
    "ALLOWED_OPERATIONS",
    "AdapterConfig",
    "BinaryPayload",
    "CallResult",
    "CapabilityResolver",
    "CapabilityState",
    "CircuitBreaker",
    "CircuitBreakerPolicy",
    "CircuitSnapshot",
    "CircuitState",
    "ClientConfigurationError",
    "DeadLetterSink",
    "Direction",
    "DirectionCapabilities",
    "DirectionHealth",
    "DirectionalClient",
    "ExternalCallError",
    "FailureClass",
    "HealthChecker",
    "HealthState",
    "HttpTransport",
    "IMPORT_OPERATIONS",
    "ItemOutcome",
    "MoodleClient",
    "MoodleClientError",
    "MoodleEndpoint",
    "MoodleHealth",
    "MoodleOperation",
    "PUBLISH_OPERATIONS",
    "ProbeResult",
    "PublicationError",
    "PublicationService",
    "ReceiptSink",
    "ReceiptValidationError",
    "ResiliencePolicy",
    "RetryPolicy",
    "SecretProvider",
    "StoredPublication",
    "TerminalOutcome",
    "TerminalReceipt",
    "TransportResponse",
    "UckkAdapter",
    "UckkCapabilitySnapshot",
    "UckkClient",
    "UckkHealthReport",
    "UckkTransport",
    "build_adapter",
    "bootstrap_adapter",
    "build_dead_letter_record",
    "build_terminal_receipt",
    "canonical_json",
    "payload_digest",
    "utc_timestamp",
)

bootstrap_adapter = build_adapter

__version__ = "1.0.0"
